version: '3.9'

services:
  php-env:
    build: . # path to Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: adepti
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql # Adăugarea unui volum pentru stocarea datelor
      - ./mysql-init:/docker-entrypoint-initdb.d # Scripturi SQL de inițializare

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8081:80
    environment:
      PMA_HOST: mysql_db
      PMA_USER: root
      PMA_PASSWORD: toor

volumes:
  mysql_data:
